### ISSUE TITLE
Podman based plugins incompatible with ZFS storage

### ISSUE THREAD

**Issue by Jip-Hop** [Jip-Hop/OMV-ZFS-RAID-NAS#3]
When trying to launch some of [the new plugins,](https://www.openmediavault.org/?p=3146) which use Podman Docker under the hood, I get: `Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver`. These plugins appear not to work currently in combination with a ZFS root filesystem. What can be done about it?

Docker, Portainer and Yacht from omv-extras work fine combined with root on ZFS, so there is the possibility to use that for containers.

```yml
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color filebrowser 2>&1' with exit code '1': debian:
----------
          ID: create_filebrowser_container_systemd_unit_file
    Function: file.managed
        Name: /etc/systemd/system/container-filebrowser.service
      Result: True
     Comment: File /etc/systemd/system/container-filebrowser.service is in the correct state
     Started: 20:47:35.432163
    Duration: 31.084 ms
     Changes:
----------
          ID: filebrowser_systemctl_daemon_reload
    Function: module.run
      Result: True
     Comment: service.systemctl_reload: True
     Started: 20:47:35.463772
    Duration: 211.447 ms
     Changes:
              ----------
              service.systemctl_reload:
                  True
----------
          ID: filebrowser_pull_app_image
    Function: cmd.run
        Name: podman pull docker.io/filebrowser/filebrowser:latest
      Result: False
     Comment: Command "podman pull docker.io/filebrowser/filebrowser:latest" run
     Started: 20:47:35.676507
    Duration: 902.874 ms
     Changes:
              ----------
              pid:
                  8493
              retcode:
                  125
              stderr:
                  time="2022-04-01T20:47:36+02:00" level=error msg="[graphdriver] prior storage driver overlay failed: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver"
                  Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
              stdout:

Summary for debian
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
Total states run:     3
Total run time:   1.145 s

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color filebrowser 2>&1' with exit code '1': debian:
----------
          ID: create_filebrowser_container_systemd_unit_file
    Function: file.managed
        Name: /etc/systemd/system/container-filebrowser.service
      Result: True
     Comment: File /etc/systemd/system/container-filebrowser.service is in the correct state
     Started: 20:47:35.432163
    Duration: 31.084 ms
     Changes:
----------
          ID: filebrowser_systemctl_daemon_reload
    Function: module.run
      Result: True
     Comment: service.systemctl_reload: True
     Started: 20:47:35.463772
    Duration: 211.447 ms
     Changes:
              ----------
              service.systemctl_reload:
                  True
----------
          ID: filebrowser_pull_app_image
    Function: cmd.run
        Name: podman pull docker.io/filebrowser/filebrowser:latest
      Result: False
     Comment: Command "podman pull docker.io/filebrowser/filebrowser:latest" run
     Started: 20:47:35.676507
    Duration: 902.874 ms
     Changes:
              ----------
              pid:
                  8493
              retcode:
                  125
              stderr:
                  time="2022-04-01T20:47:36+02:00" level=error msg="[graphdriver] prior storage driver overlay failed: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver"
                  Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
              stdout:

Summary for debian
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
Total states run:     3
Total run time:   1.145 s in /usr/share/php/openmediavault/system/process.inc:197
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(170): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusBz...', '/tmp/bgoutputTn...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(192): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

```yml
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color wetty 2>&1' with exit code '1': debian:
----------
          ID: create_wetty_container_systemd_unit_file
    Function: file.managed
        Name: /etc/systemd/system/container-wetty.service
      Result: True
     Comment: File /etc/systemd/system/container-wetty.service updated
     Started: 20:42:32.509306
    Duration: 28.453 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: wetty_systemctl_daemon_reload
    Function: module.run
      Result: True
     Comment: service.systemctl_reload: True
     Started: 20:42:32.538283
    Duration: 207.051 ms
     Changes:
              ----------
              service.systemctl_reload:
                  True
----------
          ID: wetty_pull_app_image
    Function: cmd.run
        Name: podman pull docker.io/wettyoss/wetty:latest
      Result: False
     Comment: Command "podman pull docker.io/wettyoss/wetty:latest" run
     Started: 20:42:32.746638
    Duration: 934.109 ms
     Changes:
              ----------
              pid:
                  4893
              retcode:
                  125
              stderr:
                  time="2022-04-01T20:42:33+02:00" level=error msg="[graphdriver] prior storage driver overlay failed: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver"
                  Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
              stdout:

Summary for debian
------------
Succeeded: 2 (changed=3)
Failed:    1
------------
Total states run:     3
Total run time:   1.170 s

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color wetty 2>&1' with exit code '1': debian:
----------
          ID: create_wetty_container_systemd_unit_file
    Function: file.managed
        Name: /etc/systemd/system/container-wetty.service
      Result: True
     Comment: File /etc/systemd/system/container-wetty.service updated
     Started: 20:42:32.509306
    Duration: 28.453 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: wetty_systemctl_daemon_reload
    Function: module.run
      Result: True
     Comment: service.systemctl_reload: True
     Started: 20:42:32.538283
    Duration: 207.051 ms
     Changes:
              ----------
              service.systemctl_reload:
                  True
----------
          ID: wetty_pull_app_image
    Function: cmd.run
        Name: podman pull docker.io/wettyoss/wetty:latest
      Result: False
     Comment: Command "podman pull docker.io/wettyoss/wetty:latest" run
     Started: 20:42:32.746638
    Duration: 934.109 ms
     Changes:
              ----------
              pid:
                  4893
              retcode:
                  125
              stderr:
                  time="2022-04-01T20:42:33+02:00" level=error msg="[graphdriver] prior storage driver overlay failed: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver"
                  Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
              stdout:

Summary for debian
------------
Succeeded: 2 (changed=3)
Failed:    1
------------
Total states run:     3
Total run time:   1.170 s in /usr/share/php/openmediavault/system/process.inc:197
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(170): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusoy...', '/tmp/bgoutput3t...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(192): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```
